#!/bin/sh
# Emits a C header with each shared prompt as a string constant, so the
# embedded copies cannot drift from shared/prompts/ (the self-test checks the
# files at runtime as well, like the other two apps).
set -eu
echo "/* generated by scripts/embed-prompts.sh — do not edit */"
for f in "$@"; do
  name=$(basename "$f" .txt | tr '-' '_' | tr '[:lower:]' '[:upper:]')
  printf '#define VV_PROMPT_%s \\\n' "$name"
  # Escape backslashes and quotes; each line becomes a C string with \n.
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/    "/' -e 's/$/\\n"/' "$f" | sed '$!s/$/ \\/'
  echo
done
