import Foundation
import AppKit
import Carbon.HIToolbox
import Security

/// Inserts a transcript into the frontmost app.
///
/// Strategy (informed by how VoiceInk/Maccy/Espanso ship this):
///  1. If Secure Input is active (password field / stuck agent), don't inject —
///     leave the text on the clipboard and tell the user.
///  2. Snapshot the full pasteboard (every item, every type), write the
///     transcript marked `org.nspasteboard.TransientType` + `AutoGeneratedType`
///     so clipboard managers ignore it, wait ~100 ms, post ⌘V from a private
///     event source, then restore the snapshot after a delay — but only if we
///     still own the pasteboard (the user may have copied meanwhile).
///  3. If event posting isn't available (Tahoe gates synthetic events from
///     ad-hoc-signed binaries), fall back to AppleScript `keystroke "v"`, and
///     failing that leave the transcript on the clipboard unmarked + notify.
enum PasteOutcome {
    case pasted
    case copiedOnly(reason: String)
}

final class PasteService {
    static let sessionType = NSPasteboard.PasteboardType("io.sammons.voicevector.session")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Seconds to wait before restoring the previous clipboard.
    var restoreDelay: TimeInterval = 0.9

    /// macOS 26+ silently drops synthesized modifier-bearing key events from
    /// ad-hoc-signed binaries (WindowServer gating). When that combination is
    /// detected, prefer the AppleScript path — System Events (Apple-signed)
    /// posts the keystroke instead of us.
    static let synthesizedEventsLikelyBlocked: Bool = {
        guard ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26 else { return false }
        var code: SecCode?
        guard SecCodeCopySelf([], &code) == errSecSuccess, let code else { return true }
        var staticCode: SecStaticCode?
        guard SecCodeCopyStaticCode(code, [], &staticCode) == errSecSuccess,
              let staticCode else { return true }
        var info: CFDictionary?
        guard SecCodeCopySigningInformation(staticCode, SecCSFlags(rawValue: kSecCSSigningInformation),
                                            &info) == errSecSuccess,
              let dict = info as? [String: Any] else { return true }
        // Ad-hoc signatures have no team identifier.
        return dict[kSecCodeInfoTeamIdentifier as String] == nil
    }()

    private struct Snapshot {
        var items: [[NSPasteboard.PasteboardType: Data]]
    }

    func insert(_ text: String, autoPaste: Bool, preferAppleScript: Bool = false) async -> PasteOutcome {
        let pasteboard = NSPasteboard.general
        // Trailing newlines auto-submit in chat TUIs and terminals.
        let text = text.trimmingCharacters(in: .newlines)

        guard autoPaste else {
            writePlain(text)
            return .copiedOnly(reason: "Auto-paste is off")
        }
        guard AXIsProcessTrusted() else {
            writePlain(text)
            return .copiedOnly(reason: "Accessibility permission not granted")
        }
        if IsSecureEventInputEnabled() {
            writePlain(text)
            return .copiedOnly(reason: "Secure Input is active (a password field or another app has the keyboard locked)")
        }

        let snapshot = takeSnapshot(pasteboard)
        let session = UUID().uuidString

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientType)
        item.setString("io.sammons.voicevector", forType: Self.autoGeneratedType)
        item.setString(session, forType: Self.sessionType)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])

        // Give the pasteboard server a beat before the frontmost app reads it.
        try? await Task.sleep(nanoseconds: 100_000_000)

        // The user may still be holding the hotkey (hold-to-talk): a physical
        // modifier would merge into the synthetic ⌘V (e.g. ⌥⌘V), which does
        // strange things in terminals/TUIs. Wait for release (up to ~1 s).
        await waitForModifierRelease()

        let useAppleScript = preferAppleScript || Self.synthesizedEventsLikelyBlocked
        let vKey = await MainActor.run { Self.resolveVKeyCode() }
        var posted = useAppleScript ? appleScriptPaste() : postCommandV(vKey: vKey)
        if !posted, !useAppleScript {
            posted = appleScriptPaste()
        }
        guard posted else {
            // Leave the transcript as normal clipboard content (unmarked) so it
            // persists in history, and skip the restore.
            writePlain(text)
            return .copiedOnly(reason: "Could not synthesize ⌘V — pasted text left on clipboard")
        }

        // Restore the previous clipboard later, only if we still own it.
        let delay = restoreDelay
        Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
            guard let self else { return }
            let current = NSPasteboard.general.pasteboardItems?.first?.string(forType: Self.sessionType)
            guard current == session else { return } // someone else wrote meanwhile
            self.restore(snapshot, to: NSPasteboard.general)
        }
        return .pasted
    }

    // MARK: Snapshot / restore

    private func takeSnapshot(_ pasteboard: NSPasteboard) -> Snapshot {
        var items: [[NSPasteboard.PasteboardType: Data]] = []
        for item in pasteboard.pasteboardItems ?? [] {
            var copy: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    copy[type] = data
                }
            }
            if !copy.isEmpty { items.append(copy) }
        }
        return Snapshot(items: items)
    }

    private func restore(_ snapshot: Snapshot, to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !snapshot.items.isEmpty else { return }
        let items = snapshot.items.map { stored -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in stored { item.setData(data, forType: type) }
            // Mark the restore write too, so clipboard managers don't re-record it.
            item.setData(Data(), forType: Self.transientType)
            return item
        }
        pasteboard.writeObjects(items)
    }

    private func writePlain(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    private func waitForModifierRelease() async {
        let watched: CGEventFlags = [.maskCommand, .maskAlternate, .maskControl,
                                     .maskShift, .maskSecondaryFn]
        for _ in 0..<100 {
            let flags = CGEventSource.flagsState(.hidSystemState)
            if CGEventFlags(rawValue: UInt64(flags.rawValue)).intersection(watched).isEmpty { return }
            try? await Task.sleep(nanoseconds: 10_000_000)
        }
    }

    // MARK: Key synthesis

    /// Keycode 9 is the QWERTY-V *position*; on Dvorak it types "k", turning
    /// our synthetic paste into ⌘K (clear screen!). Ask the active layout
    /// which keycode really produces "v". TIS APIs are main-thread-only
    /// (HIToolbox dispatch-asserts), hence @MainActor.
    @MainActor
    private static func resolveVKeyCode() -> CGKeyCode {
        guard let source = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue(),
              let layoutPtr = TISGetInputSourceProperty(source, kTISPropertyUnicodeKeyLayoutData) else {
            return CGKeyCode(kVK_ANSI_V)
        }
        let data = Unmanaged<CFData>.fromOpaque(layoutPtr).takeUnretainedValue() as Data
        return data.withUnsafeBytes { (buffer: UnsafeRawBufferPointer) -> CGKeyCode in
            guard let layout = buffer.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else {
                return CGKeyCode(kVK_ANSI_V)
            }
            for code in 0..<128 {
                var deadKeys: UInt32 = 0
                var chars = [UniChar](repeating: 0, count: 4)
                var length = 0
                let status = UCKeyTranslate(layout, UInt16(code), UInt16(kUCKeyActionDisplay), 0,
                                            UInt32(LMGetKbdType()), UInt32(kUCKeyTranslateNoDeadKeysBit),
                                            &deadKeys, chars.count, &length, &chars)
                if status == noErr, length == 1, chars[0] == 0x76 { // "v"
                    return CGKeyCode(code)
                }
            }
            return CGKeyCode(kVK_ANSI_V)
        }
    }

    /// Posts ⌘V (Cmd down, V down, V up, Cmd up) from a private event source so
    /// physically-held hotkey modifiers don't bleed into the synthetic events.
    private func postCommandV(vKey: CGKeyCode) -> Bool {
        guard let source = CGEventSource(stateID: .privateState) else { return false }
        let cmdKey = CGKeyCode(kVK_Command)
        guard let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: cmdKey, keyDown: true),
              let vDown = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: true),
              let vUp = CGEvent(keyboardEventSource: source, virtualKey: vKey, keyDown: false),
              let cmdUp = CGEvent(keyboardEventSource: source, virtualKey: cmdKey, keyDown: false) else {
            return false
        }
        cmdDown.flags = .maskCommand
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand
        cmdUp.flags = []
        for event in [cmdDown, vDown, vUp, cmdUp] {
            event.post(tap: .cgSessionEventTap)
            usleep(10_000)
        }
        return true
    }

    /// Fallback for environments where CGEvent posting is silently dropped
    /// (e.g. Tahoe + ad-hoc signing). Requires the Automation (System Events)
    /// permission the first time it runs.
    private func appleScriptPaste() -> Bool {
        let script = NSAppleScript(source: "tell application \"System Events\" to keystroke \"v\" using command down")
        var error: NSDictionary?
        script?.executeAndReturnError(&error)
        if let error {
            Log.error("AppleScript paste failed: \(error)")
            return false
        }
        return true
    }
}
